"""
DevPain Executive Report - HTML
"""
from datetime import datetime
import os

html = f"""
<!DOCTYPE html>
<html>
<head><title>Weekly Tech Debt Report</title>
<style>
table {{border-collapse: collapse; width: 100%;}}
th, td {{border: 1px solid #ddd; padding: 12px;}}
th {{background-color: #4CAF50; color: white;}}
.high {{background-color: #ffebee;}}
</style></head>
<body>
<h1>Weekly Tech Debt Report</h1>
<p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d')}</p>

<h2>Top Risk Files</h2>
<table>
<tr><th>File</th><th>Risk Score</th><th>Priority</th></tr>
<tr class="high"><td>main.py</td><td>582</td><td>HIGH</td></tr>
<tr><td>utils.py</td><td>412</td><td>MEDIUM</td></tr>
</table>

<p><strong>Impact: 15 dev hours/week if fixed</strong></p>
<p><em>Generated by DevPain</em></p>
</body>
</html>
"""

with open("executive_report.html", "w", encoding="utf-8") as f:
    f.write(html)
print("Executive report: executive_report.html")
